apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: ckan
  name: tb-http-loadbalancer
  annotations:
    appgw.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/ingress.class: azure/application-gateway
    cert-manager.io/cluster-issuer: letsencrypt-prod
    appgw.ingress.kubernetes.io/request-timeout: "300"
    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
    appgw.ingress.kubernetes.io/override-frontend-port: "8080"
    # CORS Security Headers - Defense in depth for CORS vulnerability
    # Note: Primary CORS control is at the application level (tb-node)
    # These annotations provide additional protection at the ingress layer
    appgw.ingress.kubernetes.io/response-headers: |
      Vary: Origin
      X-Content-Type-Options: nosniff
      X-Frame-Options: SAMEORIGIN
      X-XSS-Protection: 1; mode=block
spec:
  tls:
    - hosts:
      - ihp-wins.unesco.org
      secretName: echo-tls
  rules:
    - host: "ihp-wins.unesco.org"
      http:
        paths:
          - path: "/*"
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080