apiVersion: v1
kind: Service
metadata:
  name: tb-mqtt-loadbalancer
  namespace: ckan
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "false"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster   # <- cambiado
  selector:
    app: tb-node
  ports:
    - port: 1883
      targetPort: 1883
      name: mqtt
    - port: 8883
      targetPort: 8883
      name: mqtts
    - port: 8884
      targetPort: 8883
      name: mqtts2
    - port: 8885
      targetPort: 8883
      name: mqtts3
    - port: 8886
      targetPort: 8883
      name: mqtts4
    - name: mqtts5
      port: 8887
      targetPort: 8883